source: /docs/src/
collections_config:
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
  usage:
    path: usage
    name: Usage
    icon: image
paths:
  static: ''
  uploads: uploads
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options: {}
